name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: network_monitor
            asset_name: network_monitor-linux-amd64
          - os: macos-latest
            artifact_name: network_monitor
            asset_name: network_monitor-macos-amd64
            
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        # libpcap is usually included with Xcode Command Line Tools
        echo "libpcap should be available on macOS"
    
    - name: Build
      run: |
        g++ -o ${{ matrix.artifact_name }} main.cpp network_monitor.cpp dashboard.cpp -lpcap -lpthread
        chmod +x ${{ matrix.artifact_name }}
    
    - name: Create tarball
      run: |
        tar -czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }} README.md LICENSE
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ matrix.asset_name }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
