name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: network_monitor
            asset_name: network_monitor-linux-amd64
          - os: macos-latest
            artifact_name: network_monitor
            asset_name: network_monitor-macos-amd64
          - os: windows-latest
            artifact_name: network_monitor.exe
            asset_name: network_monitor-windows-amd64
            
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        # libpcap is usually included with Xcode Command Line Tools
        echo "libpcap should be available on macOS"
    
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install npcap -y
        choco install mingw -y
    
    - name: Build (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        g++ -o ${{ matrix.artifact_name }} main.cpp network_monitor.cpp dashboard.cpp -lpcap -lpthread
        chmod +x ${{ matrix.artifact_name }}
    
    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: |
        g++ -o ${{ matrix.artifact_name }} main.cpp network_monitor.cpp dashboard.cpp -lpacket -lws2_32 -static-libgcc -static-libstdc++ -I"C:/Program Files/Npcap/sdk/Include" -L"C:/Program Files/Npcap/sdk/Lib/x64"
    
    - name: Create tarball (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        tar -czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }} README.md LICENSE
    
    - name: Create zip archive (Windows)
      if: runner.os == 'Windows'
      run: |
        7z a ${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }} README.md LICENSE
    
    - name: Upload Release Asset (Linux/macOS)
      if: runner.os != 'Windows' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Asset (Windows)
      if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
